[package]
authors = ["charl1e7"]
categories = ["api-bindings", "asynchronous"]
description = "Free Google Translator without API key and limits."
documentation = "https://docs.rs/translators/0.1.5/translators/"
edition = "2024"
exclude = [".vscode/", "examples/", "tests/"]
homepage = "https://github.com/charl1e7/rust-translators"
keywords = ["async", "google", "language", "translate"]
license = "MIT"
name = "translators"
readme = "README.md"
repository = "https://github.com/charl1e7/rust-translators"
version = "0.1.5"

[dependencies]
html-escape = "0.2"
macon = "1.3"
regex = "1.12"
reqwest = { version = "0.13", default-features = false, features = [
  "blocking",
  "rustls",
] }
urlencoding = "2.1"
